version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "dependabot"
    groups:
      gradle-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "ci"
      - "dependabot"
    groups:
      github-actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/website"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    labels:
      - "deps"
      - "website"
      - "dependabot"
    groups:
      website-minor-patch:
        update-types:
          - "minor"
          - "patch"
