version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ci"
      - "dependabot"

  - package-ecosystem: "npm"
    directory: "/website"
    target-branch: "dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "website"
      - "dependabot"
