#
# Copyright (c) Grzegorz Kaczmarski (TajemnikTV) 2026. All rights reserved.
#
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M -XX:+UseParallelGC
org.gradle.jvmargs=-Xmx2048M -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.vfs.watch=true
