/*
 * Copyright (c) Grzegorz Kaczmarski (TajemnikTV) 2026. All rights reserved.
 */

package com.tajemniktv.tajsos.data

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/**
 * Main Room database for TajsOS.
 *
 * This database handles all persistent data including nodes (tasks, notes, etc.),
 * relationships, tracking, and external integrations like calendars.
 */
@Database(
    entities = [
        NodeEntity::class,
        TodayPinEntity::class,
        FocusSessionEntity::class,
        TrackEntryEntity::class,
        RelationEntity::class,
        TagEntity::class,
        NodeTagEntity::class,
        EventLogEntity::class,
        AttachmentEntity::class,
        TemplateEntity::class,
        CalendarProviderEntity::class,
        CalendarEventEntity::class,
        NodeSnapshotEntity::class,
        ReviewEntity::class,
    ],
    version = 20,
    exportSchema = false,
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    /**
     * Provides access to [NodeEntity] operations, representing the core data model.
     */
    abstract fun nodeDao(): NodeDao

    /**
     * Manages focus session persistence and statistics.
     */
    abstract fun focusSessionDao(): FocusSessionDao

    /**
     * Handles daily activity and progress tracking.
     */
    abstract fun trackDao(): TrackDao

    /**
     * Manages [RelationEntity] records, linking different nodes together.
     */
    abstract fun relationDao(): RelationDao

    /**
     * Handles [TagEntity] and [NodeTagEntity] operations for categorizing nodes.
     */
    abstract fun tagDao(): TagDao

    /**
     * Provides access to the system event logs for audit and sync purposes.
     */
    abstract fun eventLogDao(): EventLogDao

    /**
     * Manages file attachments and external links associated with nodes.
     */
    abstract fun attachmentDao(): AttachmentDao

    /**
     * Handles node templates for quick creation of pre-defined structures.
     */
    abstract fun templateDao(): TemplateDao

    /**
     * Manages external calendar source configurations.
     */
    abstract fun calendarProviderDao(): CalendarProviderDao

    /**
     * Handles cached calendar events synced from external providers.
     */
    abstract fun calendarEventDao(): CalendarEventDao

    /**
     * Stores historical versions of nodes.
     */
    abstract fun nodeSnapshotDao(): NodeSnapshotDao

    /**
     * Manages formal review sessions.
     */
    abstract fun reviewDao(): ReviewDao
}

/**
 * Constructor for [AppDatabase] generated by Room.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    /**
     * Initializes the [AppDatabase].
     */
    override fun initialize(): AppDatabase
}

/**
 * Configures and builds the [AppDatabase] instance.
 *
 * @param builder The platform-specific Room database builder.
 * @return A fully initialized [AppDatabase] instance.
 */
fun getDatabaseBuilder(builder: RoomDatabase.Builder<AppDatabase>): AppDatabase =
    builder
        .build()
